### ISSUE TITLE
downsample probelm

### ISSUE THREAD

**Issue by yanyu003** [IntelVCL/Open3D-PointNet2-Semantic3D#27]
There is an error in downsample.py:
 module 'open3d.open3d' has no attribute 'voxel_down_sample_and_trace'?

my open3d is installed form conda, and its version is 0.40.0.

**Comment by yxlao** [comment]
Please compile from source using the `master` branch. `voxel_down_sample_and_trace` is available on   `master` and will be available in 0.5.0. 

Since we are using Open3D C++ for [TF custom ops](https://github.com/IntelVCL/Open3D-PointNet2-Semantic3D#4-compile-tf-ops), we need to compile from source anyway (at least the header is needed).

**Comment by yanyu003** [comment]
Thank you very much, It works now.
